"""V6 execution surface for exact HOLD / CONTINUOUS / EXIT actions."""

from __future__ import annotations

from dataclasses import dataclass

import torch

from rl_quant.models.daily_policy import hold30_release_hazard
from rl_quant.models.hold30_exit_action_v6 import M03RV6ExitAction
from rl_quant.protocol.hold30_alpha_m03r_v6 import M03R_AGE_LEDGER_BIN_COUNT


class M03RV6ExitExecutionError(ValueError):
    """A v6 exit action cannot be applied to the supplied age ledger."""


@dataclass(frozen=True, slots=True)
class M03RV6ExitRelease:
    """Differentiable discretionary release generated by one v6 model action."""

    action: M03RV6ExitAction
    continuous_release_fraction_by_age: torch.Tensor
    effective_release_fraction_by_age: torch.Tensor
    discretionary_release_by_age: torch.Tensor
    discretionary_release: torch.Tensor

    def __post_init__(self) -> None:
        self.validate()

    def validate(self) -> None:
        """Revalidate mutable tensor contents and conservation identities."""

        self.action.validate()
        expected = (*self.action.risky_available.shape, M03R_AGE_LEDGER_BIN_COUNT)
        for name in (
            "continuous_release_fraction_by_age",
            "effective_release_fraction_by_age",
            "discretionary_release_by_age",
        ):
            value = getattr(self, name)
            if (
                not isinstance(value, torch.Tensor)
                or tuple(value.shape) != expected
                or not value.is_floating_point()
                or not bool(torch.isfinite(value).all())
            ):
                raise M03RV6ExitExecutionError(
                    f"{name} must be finite floating [batch,asset,61]"
                )
        if (
            not isinstance(self.discretionary_release, torch.Tensor)
            or tuple(self.discretionary_release.shape)
            != tuple(self.action.risky_available.shape)
            or not self.discretionary_release.is_floating_point()
            or not bool(torch.isfinite(self.discretionary_release).all())
        ):
            raise M03RV6ExitExecutionError(
                "discretionary_release must be finite floating [batch,asset]"
            )
        for name in (
            "continuous_release_fraction_by_age",
            "effective_release_fraction_by_age",
        ):
            value = getattr(self, name)
            if bool(((value < 0.0) | (value > 1.0)).any()):
                raise M03RV6ExitExecutionError(f"{name} must lie in [0,1]")
        if bool((self.discretionary_release_by_age < 0.0).any()) or bool(
            (self.discretionary_release < 0.0).any()
        ):
            raise M03RV6ExitExecutionError("release notional cannot be negative")
        if not bool(
            torch.allclose(
                self.discretionary_release_by_age.sum(dim=-1),
                self.discretionary_release,
                atol=1e-8,
                rtol=1e-8,
            )
        ):
            raise M03RV6ExitExecutionError(
                "discretionary release does not conserve its age bins"
            )
        unavailable = ~self.action.risky_available
        if bool(unavailable.any()) and (
            bool((self.effective_release_fraction_by_age[unavailable] != 0.0).any())
            or bool((self.discretionary_release_by_age[unavailable] != 0.0).any())
        ):
            raise M03RV6ExitExecutionError(
                "CASH/unavailable HOLD sentinels must release exactly zero"
            )


def build_m03r_v6_exit_release(
    age_notional: torch.Tensor,
    hazard_residual: torch.Tensor,
    action: M03RV6ExitAction,
) -> M03RV6ExitRelease:
    """Apply one exact three-way model action to cohort notionals.

    HOLD releases exactly zero, EXIT releases every held cohort exactly, and
    CONTINUOUS delegates to the existing age-aware smooth hazard.  The hard
    forward decisions retain the action head's straight-through softmax
    gradient, so an economic loss can learn to cross either exact branch.
    """

    if not isinstance(action, M03RV6ExitAction):
        raise M03RV6ExitExecutionError("action must be M03RV6ExitAction")
    action.validate()
    if (
        not isinstance(age_notional, torch.Tensor)
        or age_notional.ndim != 3
        or age_notional.shape[-1] != M03R_AGE_LEDGER_BIN_COUNT
        or tuple(age_notional.shape[:-1]) != tuple(action.risky_available.shape)
        or not age_notional.is_floating_point()
        or not bool(torch.isfinite(age_notional).all())
        or bool((age_notional < 0.0).any())
    ):
        raise M03RV6ExitExecutionError(
            "age_notional must be finite nonnegative floating [batch,asset,61]"
        )
    if (
        not isinstance(hazard_residual, torch.Tensor)
        or tuple(hazard_residual.shape) != tuple(action.risky_available.shape)
        or not hazard_residual.is_floating_point()
        or not bool(torch.isfinite(hazard_residual).all())
    ):
        raise M03RV6ExitExecutionError(
            "hazard_residual must be finite floating [batch,asset]"
        )
    if (
        hazard_residual.device != age_notional.device
        or action.logits.device != age_notional.device
    ):
        raise M03RV6ExitExecutionError(
            "ledger, hazard, and action tensors must share one device"
        )
    dtype = age_notional.dtype
    ages = torch.arange(
        M03R_AGE_LEDGER_BIN_COUNT,
        device=age_notional.device,
        dtype=dtype,
    )
    continuous = hold30_release_hazard(
        ages,
        hazard_residual.to(dtype=dtype).unsqueeze(-1),
    )
    # Normalization roundoff can otherwise produce 1+epsilon in FP32. Keep the
    # continuous branch strictly below one so only the explicit EXIT atom can
    # release every cohort exactly, as required by the v6 protocol.
    continuous_upper = torch.nextafter(
        torch.ones((), device=age_notional.device, dtype=dtype),
        torch.zeros((), device=age_notional.device, dtype=dtype),
    )
    continuous = torch.minimum(continuous.clamp_min(0.0), continuous_upper)
    continuous_decision = action.continuous_decision_st.to(dtype=dtype).unsqueeze(-1)
    exit_decision = action.exit_decision_st.to(dtype=dtype).unsqueeze(-1)
    effective = exit_decision + continuous_decision * continuous
    effective = torch.where(
        action.risky_available.unsqueeze(-1),
        effective,
        torch.zeros_like(effective),
    )
    released_by_age = age_notional * effective
    released = released_by_age.sum(dim=-1)
    result = M03RV6ExitRelease(
        action=action,
        continuous_release_fraction_by_age=continuous,
        effective_release_fraction_by_age=effective,
        discretionary_release_by_age=released_by_age,
        discretionary_release=released,
    )
    if bool((released_by_age - age_notional > 1e-8).any()):
        raise M03RV6ExitExecutionError("v6 action released more than held notional")
    return result


__all__ = [
    "M03RV6ExitExecutionError",
    "M03RV6ExitRelease",
    "build_m03r_v6_exit_release",
]
